# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75665b7f30268fb23b097a25ddab533d9bf042681bbfae6f603662f476163efc33c60ce535e8708c0b43e69c7cde6b95f8d6b98165e501772b817e384a32e6e

test:
  secret_key_base: 159c83d1244be515023d46ea199f077049cb977abd5b9f8bff836d20f8992a0477cf73005dfb3fa7af439f4756ba2d3be7ba95bd1d6bfaf3d125b4ad2bf3d169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
