# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d672f2c6353bdffe196d5059387d59ab9df8d43383b681a5f801b65bacf273844806ae0a8281a73ac8e778005c0c6b5f51f18f9b87270b05bb25efb5ece79453

test:
  secret_key_base: 5d8428297352f2df4a096e14e2342d0d1c17ea7f86d1408f711c1bb5435681599291049525beea6977b5d68575b3293d512bc8297196aa49946264bab312e37a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
